name: RunUnitTests
# Triggers the workflow on push or pull request events
on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 4.7.2
      - name: Restore dependencies
        run: dotnet restore ReceptTracker/ReceptTracker.Unit
      - name: Build
        run: dotnet build ReceptTracker/ReceptTracker.Unit --no-restore
      - name: Test
        run: dotnet test ReceptTracker/ReceptTracker.Unit --no-restore
